# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e5cf0c81-8c86-49a8-a34c-82f5ad2779c8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e5cf0c81-8c86-49a8-a34c-82f5ad2779c8".device = "/dev/disk/by-uuid/e5cf0c81-8c86-49a8-a34c-82f5ad2779c8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7BFC-94C7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-af657024-09f5-4039-9d50-8574d7726cbe"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
